export const InventoryCapabilities = {
  warehouseRead: "inventory.warehouse.read",
  warehouseCreate: "inventory.warehouse.create",
  itemRead: "inventory.item.read",
  itemCreate: "inventory.item.create",
  stockRead: "inventory.stock.read",
  stockReceive: "inventory.stock.receive",
  stockAdjust: "inventory.stock.adjust",
  stockReserve: "inventory.stock.reserve",
  stockRelease: "inventory.stock.release",
  stockFulfill: "inventory.stock.fulfill",
  stockTransferCreate: "inventory.stock_transfer.create",
  stockTransferConfirm: "inventory.stock_transfer.confirm",
  stockTransferComplete: "inventory.stock_transfer.complete",
} as const
