import * as Schema from "effect/Schema"
import * as SchemaRepresentation from "effect/SchemaRepresentation"

import {
  Capability,
  CapabilityScope,
  CapabilityStability,
  DirectCapabilityGrant,
  TenantMembership,
  TenantMembershipStatus,
} from "../../modules/authorization/mod.ts"
import {
  CreateUserAccountInput,
  UpdateUserAccountInput,
  UserAccount,
} from "../../modules/identity/mod.ts"
import { PurchaseOrderStatus, SupplierAccount } from "../../modules/procurement/mod.ts"
import {
  ProcessCatalogCapabilityKind,
  ProcessCatalogDescriptor,
  ProcessEnvironment,
  ProcessFailureKind,
  ProcessJobInboxItem,
  ProcessOperatorAction,
  ProcessOperatorControl,
  ProcessOperatorInbox,
  ProcessRuntimeInstance,
  ProcessRuntimeStatus,
  ProcessStaticValidation,
  ProcessWorkflowRun,
  ProcessWorkflowType,
  ResolveProcessCatalogInput,
} from "../../modules/process/mod.ts"
import {
  Branch,
  ExternalIdentifier,
  LegalEntity,
  Party,
  PartyDetail,
  PartyDirectoryEntry,
  PartyKind,
  PartyRelationship,
  PartyRelationshipKind,
  PartyRepresentation,
  PartyRepresentationKind,
  PartyRole,
  RelatedPartyPath,
} from "../../modules/party/mod.ts"
import {
  ApiConflict,
  ApiForbidden,
  ApiNotFound,
  ApiServiceUnavailable,
  ApiUnauthorized,
  AuthConfiguration,
  AuthLoginResult,
  AuthProfile,
  AuthSession,
  RitseiApi,
} from "../../runtime/api/api.ts"

const ApiError = Schema.Union([
  ApiUnauthorized,
  ApiForbidden,
  ApiNotFound,
  ApiConflict,
  ApiServiceUnavailable,
])
const NonEmptyString = Schema.String.check(Schema.isPattern(/\S/))
const ShortString = Schema.String.check(Schema.isPattern(/\S/), Schema.isMaxLength(256))
const Uuid = Schema.String.check(Schema.isUUID())
const Limit = Schema.optionalKey(Schema.Number.pipe(
  Schema.check(Schema.isInt()),
  Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
))

const declarations = (schemas: Record<string, Schema.Top>): ReadonlyArray<string> =>
  Object.entries(schemas).map(([name, schema]) => {
    const representation = SchemaRepresentation.toRepresentation(schema.ast, {
      referencePolicy: () => undefined,
    })
    const document = SchemaRepresentation.toCodeDocument(
      SchemaRepresentation.toMultiDocument(representation),
    )
    if (
      document.artifacts.length > 0 ||
      document.references.nonRecursives.length > 0 ||
      Object.keys(document.references.recursives).length > 0 ||
      Object.keys(representation.references).length > 0 ||
      document.codes.length !== 1
    ) {
      throw new Error(`Unsupported browser contract artifacts or references: ${name}`)
    }
    return `export const ${name} = ${document.codes[0]!.runtime}\n` +
      `export type ${name} = Schema.Schema.Type<typeof ${name}>`
  })

export function source(): string {
  const generated = declarations({
    UserAccount,
    CreateUserAccountInput,
    UpdateUserAccountInput,
    ApiError,
  })
  const endpoints = RitseiApi.groups.UserAccounts.endpoints
  return [
    "// Generated by tooling/frontend/contracts.ts. Do not edit.",
    'import * as Schema from "effect/Schema"',
    ...generated,
    `export const userAccountRoutes = ${
      JSON.stringify({
        create: endpoints.create.path,
        list: endpoints.list.path,
        get: endpoints.get.path,
        update: endpoints.update.path,
      })
    } as const`,
    "",
  ].join("\n\n")
}

export function authorizationSource(): string {
  const generated = declarations({
    TenantMembershipStatus,
    TenantMembership,
    DirectCapabilityGrant,
    Capability,
    CapabilityScope,
    CapabilityStability,
    CapabilityDefinition: Schema.Struct({
      id: Capability,
      owner: Schema.String.check(Schema.isPattern(/^[a-z][a-z0-9_]*$/)),
      resource: Schema.String.check(Schema.isPattern(/^[a-z][a-z0-9_]*$/)),
      verb: Schema.String.check(Schema.isPattern(/^[a-z][a-z0-9_]*$/)),
      version: Schema.Int,
      stability: CapabilityStability,
      scope: Schema.Array(CapabilityScope),
    }),
    ListTenantMembershipsInput: Schema.Struct({
      search: Schema.optionalKey(Schema.Trim.pipe(
        Schema.check(Schema.isPattern(/\S/)),
        Schema.check(Schema.isMaxLength(256)),
      )),
      status: Schema.optionalKey(TenantMembershipStatus),
      limit: Schema.optionalKey(Schema.Int.check(
        Schema.isBetween({ minimum: 1, maximum: 200 }),
      )),
    }),
    AddTenantMembershipInput: Schema.Struct({ userAccountId: Uuid }),
    GrantCapabilityInput: Schema.Struct({ userAccountId: Uuid, capability: Capability }),
    ApiError,
  })
  const endpoints = RitseiApi.groups.Authorization.endpoints
  return [
    "// Generated by tooling/frontend/contracts.ts. Do not edit.",
    'import * as Schema from "effect/Schema"',
    ...generated,
    `export const authorizationRoutes = ${
      JSON.stringify({
        list: endpoints.listMembers.path,
        get: endpoints.getMember.path,
        add: endpoints.addMember.path,
        listDirectGrants: endpoints.listDirectGrants.path,
        listCapabilityDefinitions: endpoints.listCapabilityDefinitions.path,
        suspend: endpoints.suspendMember.path,
        activate: endpoints.activateMember.path,
        remove: endpoints.removeMember.path,
        grant: endpoints.grant.path,
      })
    } as const`,
    "",
  ].join("\n\n")
}

export function procurementSource(): string {
  const Quantity = Schema.String.check(Schema.isPattern(/^[1-9]\d*$/))
  const Money = Schema.String.check(Schema.isPattern(/^\d+\.\d{2}$/))
  const PurchaseOrderLine = Schema.Struct({ itemId: Uuid, quantity: Quantity, unitPrice: Money })
  const PurchaseOrderLineSnapshot = Schema.Struct({
    id: Uuid,
    itemId: Uuid,
    quantity: Quantity,
    unitPrice: Money,
  })
  const BrowserPurchaseOrder = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    supplierAccountId: Uuid,
    status: PurchaseOrderStatus,
    confirmedAt: Schema.NullOr(Schema.String),
    total: Money,
    lines: Schema.Array(PurchaseOrderLineSnapshot).check(Schema.isMinLength(1)),
  })
  const PurchaseReceiptLineInput = Schema.Struct({
    purchaseOrderLineId: Uuid,
    quantity: Quantity,
  })
  const GoodsReceiptLine = Schema.Struct({
    id: Uuid,
    purchaseOrderLineId: Uuid,
    itemId: Uuid,
    quantity: Quantity,
    unitOfMeasure: Schema.String.check(Schema.isPattern(/^[A-Z][A-Z0-9_-]*$/)),
  })
  const BrowserGoodsReceipt = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    purchaseOrderId: Uuid,
    warehouseId: Uuid,
    idempotencyKey: ShortString,
    receivedAt: Schema.String,
    lines: Schema.Array(GoodsReceiptLine).check(Schema.isMinLength(1)),
  })
  const generated = declarations({
    SupplierAccount,
    PurchaseOrderStatus,
    PurchaseOrderLine,
    PurchaseOrder: BrowserPurchaseOrder,
    GoodsReceipt: BrowserGoodsReceipt,
    PurchaseReceiptLineInput,
    ListSupplierAccountsInput: Schema.Struct({
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    CreateSupplierAccountInput: Schema.Struct({ supplierRelationshipId: Uuid }),
    ListPurchaseOrdersInput: Schema.Struct({
      supplierAccountId: Schema.optionalKey(Uuid),
      status: Schema.optionalKey(PurchaseOrderStatus),
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    CreatePurchaseOrderInput: Schema.Struct({
      supplierAccountId: Uuid,
      lines: Schema.Array(PurchaseOrderLine).check(Schema.isMinLength(1)),
    }),
    ConfirmPurchaseOrderInput: Schema.Struct({ idempotencyKey: ShortString }),
    ListPurchaseReceiptsInput: Schema.Struct({
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    ReceivePurchaseOrderInput: Schema.Struct({
      warehouseId: Uuid,
      idempotencyKey: ShortString,
      lines: Schema.Array(PurchaseReceiptLineInput).check(Schema.isMinLength(1)),
    }),
    ApiError,
  })
  const endpoints = RitseiApi.groups.Procurement.endpoints
  return [
    "// Generated by tooling/frontend/contracts.ts. Do not edit.",
    'import * as Schema from "effect/Schema"',
    ...generated,
    `export const procurementRoutes = ${
      JSON.stringify({
        listSupplierAccounts: endpoints.listSupplierAccounts.path,
        createSupplierAccount: endpoints.createSupplierAccount.path,
        listPurchaseOrders: endpoints.listPurchaseOrders.path,
        createPurchaseOrder: endpoints.createPurchaseOrder.path,
        getPurchaseOrder: endpoints.getPurchaseOrder.path,
        confirmPurchaseOrder: endpoints.confirmPurchaseOrder.path,
        cancelPurchaseOrder: endpoints.cancelPurchaseOrder.path,
        listPurchaseReceipts: endpoints.listPurchaseReceipts.path,
        receivePurchaseOrder: endpoints.receivePurchaseOrder.path,
      })
    } as const`,
    "",
  ].join("\n\n")
}

export function inventorySource(): string {
  const Quantity = Schema.String.check(Schema.isPattern(/^[1-9]\d*$/))
  const SignedQuantity = Schema.String.check(Schema.isPattern(/^-?[1-9]\d*$/))
  const UnitOfMeasure = Schema.String.check(Schema.isPattern(/^[A-Z][A-Z0-9_-]*$/))
  const StockReservationStatus = Schema.Literals(["active", "released", "fulfilled"])
  const StockTransferStatus = Schema.Literals(["draft", "confirmed", "completed"])
  const StockMovementKind = Schema.Literals(["receipt", "issue", "reservation", "release"])
  const Warehouse = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    legalEntityId: Uuid,
    primaryBranchId: Schema.NullOr(Uuid),
    name: NonEmptyString,
  })
  const Item = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    sku: NonEmptyString,
    name: NonEmptyString,
    unitOfMeasure: UnitOfMeasure,
  })
  const StockBalance = Schema.Struct({
    tenantId: Uuid,
    warehouseId: Uuid,
    itemId: Uuid,
    onHand: Schema.String.check(Schema.isPattern(/^(0|[1-9]\d*)$/)),
    reserved: Schema.String.check(Schema.isPattern(/^(0|[1-9]\d*)$/)),
    unitOfMeasure: UnitOfMeasure,
  })
  const StockCorrection = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    warehouseId: Uuid,
    itemId: Uuid,
    adjustment: SignedQuantity,
    unitOfMeasure: UnitOfMeasure,
    reason: NonEmptyString,
    idempotencyKey: ShortString,
  })
  const StockReservation = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    warehouseId: Uuid,
    itemId: Uuid,
    quantity: Quantity,
    idempotencyKey: Schema.NullOr(ShortString),
    status: StockReservationStatus,
  })
  const StockTransferLine = Schema.Struct({ itemId: Uuid, quantity: Quantity })
  const StockTransfer = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    legalEntityId: Uuid,
    sourceWarehouseId: Uuid,
    destinationWarehouseId: Uuid,
    status: StockTransferStatus,
    confirmedAt: Schema.NullOr(Schema.String),
    completedAt: Schema.NullOr(Schema.String),
    lines: Schema.Array(StockTransferLine).check(Schema.isMinLength(1)),
  })
  const StockMovement = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    warehouseId: Uuid,
    itemId: Uuid,
    quantity: SignedQuantity,
    kind: StockMovementKind,
    referenceId: Schema.NullOr(Uuid),
    unitOfMeasure: Schema.NullOr(UnitOfMeasure),
    reason: Schema.NullOr(ShortString),
    idempotencyKey: Schema.NullOr(ShortString),
  })
  const generated = declarations({
    Warehouse,
    Item,
    StockBalance,
    StockCorrection,
    StockReservationStatus,
    StockReservation,
    StockTransferStatus,
    StockTransferLine,
    StockTransfer,
    StockMovementKind,
    StockMovement,
    ListWarehousesInput: Schema.Struct({
      legalEntityId: Schema.optionalKey(Uuid),
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    ListItemsInput: Schema.Struct({
      search: Schema.optionalKey(Schema.Trim.pipe(
        Schema.check(Schema.isPattern(/\S/)),
        Schema.check(Schema.isMaxLength(256)),
      )),
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    ListStockBalancesInput: Schema.Struct({
      warehouseId: Schema.optionalKey(Uuid),
      itemId: Schema.optionalKey(Uuid),
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    ListStockReservationsInput: Schema.Struct({
      warehouseId: Schema.optionalKey(Uuid),
      itemId: Schema.optionalKey(Uuid),
      status: Schema.optionalKey(StockReservationStatus),
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    ListStockTransfersInput: Schema.Struct({
      warehouseId: Schema.optionalKey(Uuid),
      status: Schema.optionalKey(StockTransferStatus),
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    ListStockMovementsInput: Schema.Struct({
      warehouseId: Schema.optionalKey(Uuid),
      itemId: Schema.optionalKey(Uuid),
      kind: Schema.optionalKey(StockMovementKind),
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    CreateWarehouseInput: Schema.Struct({
      legalEntityId: Uuid,
      primaryBranchId: Schema.optionalKey(Uuid),
      name: NonEmptyString,
    }),
    CreateItemInput: Schema.Struct({
      sku: NonEmptyString,
      name: NonEmptyString,
      unitOfMeasure: Schema.optionalKey(ShortString),
    }),
    AdjustStockInput: Schema.Struct({
      warehouseId: Uuid,
      itemId: Uuid,
      adjustment: NonEmptyString,
      unitOfMeasure: ShortString,
      reason: ShortString,
      commandId: ShortString,
      correlationId: ShortString,
      causationId: Schema.optionalKey(Schema.NullOr(ShortString)),
      idempotencyKey: ShortString,
    }),
    ReceiveStockInput: Schema.Struct({
      warehouseId: Uuid,
      itemId: Uuid,
      quantity: NonEmptyString,
      legalEntityId: Schema.optionalKey(Uuid),
      referenceId: Schema.optionalKey(Uuid),
    }),
    ReserveStockInput: Schema.Struct({
      warehouseId: Uuid,
      itemId: Uuid,
      quantity: NonEmptyString,
      legalEntityId: Schema.optionalKey(Uuid),
      idempotencyKey: Schema.optionalKey(ShortString),
    }),
    CreateStockTransferInput: Schema.Struct({
      sourceWarehouseId: Uuid,
      destinationWarehouseId: Uuid,
      lines: Schema.Array(StockTransferLine).check(Schema.isMinLength(1)),
    }),
    ApiError,
  })
  const endpoints = RitseiApi.groups.Inventory.endpoints
  return [
    "// Generated by tooling/frontend/contracts.ts. Do not edit.",
    'import * as Schema from "effect/Schema"',
    ...generated,
    `export const inventoryRoutes = ${
      JSON.stringify({
        listWarehouses: endpoints.listWarehouses.path,
        createWarehouse: endpoints.createWarehouse.path,
        listItems: endpoints.listItems.path,
        createItem: endpoints.createItem.path,
        listStockBalances: endpoints.listStockBalances.path,
        adjustStock: endpoints.adjustStock.path,
        receiveStock: endpoints.receiveStock.path,
        listStockReservations: endpoints.listStockReservations.path,
        reserveStock: endpoints.reserveStock.path,
        releaseReservation: endpoints.releaseReservation.path,
        fulfillReservation: endpoints.fulfillReservation.path,
        listStockTransfers: endpoints.listStockTransfers.path,
        createTransfer: endpoints.createTransfer.path,
        confirmTransfer: endpoints.confirmTransfer.path,
        completeTransfer: endpoints.completeTransfer.path,
        listStockMovements: endpoints.listStockMovements.path,
      })
    } as const`,
    "",
  ].join("\n\n")
}

export function salesSource(): string {
  const Money = Schema.String.check(Schema.isPattern(/^\d+\.\d{2}$/))
  const Quantity = Schema.String.check(Schema.isPattern(/^[1-9]\d*$/))
  const QuotationStatus = Schema.Literals(["draft", "sent", "accepted", "rejected", "expired"])
  const SalesOrderStatus = Schema.Literals(["draft", "confirmed", "cancelled"])
  const Customer = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    name: NonEmptyString,
    email: Schema.String.check(Schema.isPattern(/^[^\s@]+@[^\s@]+$/)),
  })
  const Quotation = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    customerId: Uuid,
    status: QuotationStatus,
    total: Money,
  })
  const SalesOrderLine = Schema.Struct({ itemId: Uuid, quantity: Quantity, unitPrice: Money })
  const SalesOrder = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    customerId: Uuid,
    quotationId: Schema.NullOr(Uuid),
    status: SalesOrderStatus,
    confirmedAt: Schema.NullOr(Schema.String),
    total: Money,
    lines: Schema.Array(SalesOrderLine).check(Schema.isMinLength(1)),
  })
  const generated = declarations({
    Customer,
    QuotationStatus,
    Quotation,
    SalesOrderStatus,
    SalesOrderLine,
    SalesOrder,
    ListCustomersInput: Schema.Struct({
      search: Schema.optionalKey(Schema.Trim.pipe(
        Schema.check(Schema.isPattern(/\S/)),
        Schema.check(Schema.isMaxLength(256)),
      )),
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    GetCustomerInput: Schema.Struct({ customerId: Uuid }),
    CreateCustomerInput: Schema.Struct({
      name: NonEmptyString,
      email: Schema.String.check(Schema.isPattern(/^[^\s@]+@[^\s@]+$/)),
    }),
    ListQuotationsInput: Schema.Struct({
      customerId: Schema.optionalKey(Uuid),
      status: Schema.optionalKey(QuotationStatus),
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    GetQuotationInput: Schema.Struct({ quotationId: Uuid }),
    CreateQuotationInput: Schema.Struct({ customerId: Uuid, total: Money }),
    ListOrdersInput: Schema.Struct({
      customerId: Schema.optionalKey(Uuid),
      status: Schema.optionalKey(SalesOrderStatus),
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    GetOrderInput: Schema.Struct({ orderId: Uuid }),
    CreateOrderInput: Schema.Struct({
      customerId: Uuid,
      quotationId: Schema.optionalKey(Uuid),
      lines: Schema.Array(SalesOrderLine).check(Schema.isMinLength(1)),
    }),
    ConfirmOrderInput: Schema.Struct({
      commandId: ShortString,
      correlationId: ShortString,
      causationId: Schema.optionalKey(Schema.NullOr(ShortString)),
      idempotencyKey: ShortString,
    }),
    ApiError,
  })
  const endpoints = RitseiApi.groups.Sales.endpoints
  return [
    "// Generated by tooling/frontend/contracts.ts. Do not edit.",
    'import * as Schema from "effect/Schema"',
    ...generated,
    `export const salesRoutes = ${
      JSON.stringify({
        listCustomers: endpoints.listCustomers.path,
        getCustomer: endpoints.getCustomer.path,
        createCustomer: endpoints.createCustomer.path,
        listQuotations: endpoints.listQuotations.path,
        getQuotation: endpoints.getQuotation.path,
        createQuotation: endpoints.createQuotation.path,
        listOrders: endpoints.listOrders.path,
        getOrder: endpoints.getOrder.path,
        createOrder: endpoints.createOrder.path,
        confirmOrder: endpoints.confirmOrder.path,
        cancelOrder: endpoints.cancelOrder.path,
      })
    } as const`,
    "",
  ].join("\n\n")
}

export function accountingSource(): string {
  const Money = Schema.String.check(Schema.isPattern(/^\d{1,18}(\.\d{1,2})?$/))
  const AccountType = Schema.Literals(["asset", "liability", "equity", "revenue", "expense"])
  const AccountingPeriodStatus = Schema.Literals(["open", "closed"])
  const JournalStatus = Schema.Literals(["posted", "reversed"])
  const AccountingConfiguration = Schema.Struct({
    tenantId: Uuid,
    legalEntityId: Uuid,
    baseCurrency: Schema.String.check(Schema.isPattern(/^[A-Z]{3}$/)),
    precision: Schema.Literal(2),
    fiscalYearStartMonth: Schema.Number.pipe(
      Schema.check(Schema.isInt()),
      Schema.check(Schema.isBetween({ minimum: 1, maximum: 12 })),
    ),
    postingEnabled: Schema.Boolean,
    financialEngine: Schema.Literals(["postgresql", "tigerbeetle"]),
  })
  const Account = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    code: NonEmptyString,
    name: NonEmptyString,
    type: AccountType,
  })
  const AccountingPeriod = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    legalEntityId: Uuid,
    startsOn: Schema.String.check(Schema.isPattern(/^\d{4}-\d{2}-\d{2}$/)),
    endsOn: Schema.String.check(Schema.isPattern(/^\d{4}-\d{2}-\d{2}$/)),
    status: AccountingPeriodStatus,
  })
  const RevenuePostingProfile = Schema.Struct({
    tenantId: Uuid,
    legalEntityId: Uuid,
    receivableAccountId: Uuid,
    revenueAccountId: Uuid,
  })
  const JournalLine = Schema.Struct({ accountId: Uuid, debit: Money, credit: Money })
  const JournalEntry = Schema.Struct({
    id: Uuid,
    tenantId: Uuid,
    reference: NonEmptyString,
    status: JournalStatus,
    postedAt: Schema.String,
    reversesEntryId: Schema.optionalKey(Uuid),
    lines: Schema.Array(JournalLine).check(Schema.isMinLength(2)),
  })
  const generated = declarations({
    AccountType,
    AccountingPeriodStatus,
    JournalStatus,
    AccountingConfiguration,
    Account,
    AccountingPeriod,
    RevenuePostingProfile,
    JournalLine,
    JournalEntry,
    ListAccountingConfigurationsInput: Schema.Struct({
      legalEntityId: Schema.optionalKey(Uuid),
      limit: Limit,
    }),
    ListAccountsInput: Schema.Struct({
      type: Schema.optionalKey(AccountType),
      limit: Limit,
    }),
    ListAccountingPeriodsInput: Schema.Struct({
      legalEntityId: Schema.optionalKey(Uuid),
      status: Schema.optionalKey(AccountingPeriodStatus),
      limit: Limit,
    }),
    ListRevenuePostingProfilesInput: Schema.Struct({
      legalEntityId: Schema.optionalKey(Uuid),
      limit: Limit,
    }),
    ListJournalEntriesInput: Schema.Struct({
      status: Schema.optionalKey(JournalStatus),
      limit: Limit,
    }),
    ConfigureLegalEntityInput: Schema.Struct({
      baseCurrency: Schema.String.check(Schema.isPattern(/^[A-Z]{3}$/)),
      precision: Schema.Literal(2),
      fiscalYearStartMonth: Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 12 })),
      ),
      postingEnabled: Schema.Boolean,
      financialEngine: Schema.optionalKey(Schema.Literals(["postgresql", "tigerbeetle"])),
    }),
    CreateAccountInput: Schema.Struct({
      code: NonEmptyString,
      name: NonEmptyString,
      type: AccountType,
    }),
    ConfigureRevenuePostingInput: Schema.Struct({
      legalEntityId: Uuid,
      receivableAccountId: Uuid,
      revenueAccountId: Uuid,
    }),
    OpenPeriodInput: Schema.Struct({
      legalEntityId: Uuid,
      startsOn: Schema.String.check(Schema.isPattern(/^\d{4}-\d{2}-\d{2}$/)),
      endsOn: Schema.String.check(Schema.isPattern(/^\d{4}-\d{2}-\d{2}$/)),
    }),
    ClosePeriodInput: Schema.Struct({ legalEntityId: Uuid }),
    PostJournalInput: Schema.Struct({
      reference: NonEmptyString,
      lines: Schema.Array(JournalLine).check(Schema.isMinLength(2)),
    }),
    ApiError,
  })
  const endpoints = RitseiApi.groups.Accounting.endpoints
  return [
    "// Generated by tooling/frontend/contracts.ts. Do not edit.",
    'import * as Schema from "effect/Schema"',
    ...generated,
    `export const accountingRoutes = ${
      JSON.stringify({
        listConfigurations: endpoints.listConfigurations.path,
        listAccounts: endpoints.listAccounts.path,
        listPeriods: endpoints.listPeriods.path,
        listRevenuePostingProfiles: endpoints.listRevenuePostingProfiles.path,
        listJournals: endpoints.listJournals.path,
        configureLegalEntity: endpoints.configureLegalEntity.path,
        createAccount: endpoints.createAccount.path,
        configureRevenuePosting: endpoints.configureRevenuePosting.path,
        openPeriod: endpoints.openPeriod.path,
        closePeriod: endpoints.closePeriod.path,
        postJournal: endpoints.postJournal.path,
      })
    } as const`,
    "",
  ].join("\n\n")
}

export function processSource(): string {
  const generated = declarations({
    ProcessCatalogCapabilityKind,
    ProcessCatalogDescriptor,
    ProcessFailureKind,
    ProcessRuntimeStatus,
    ProcessEnvironment,
    ProcessRuntimeInstance,
    ProcessWorkflowType,
    ProcessWorkflowRun,
    ProcessJobInboxItem,
    ProcessOperatorAction,
    ProcessOperatorControl,
    ProcessOperatorInbox,
    ProcessStaticValidation,
    ResolveProcessCatalogInput,
    ListProcessCatalogInput: Schema.Struct({
      kind: Schema.optionalKey(ProcessCatalogCapabilityKind),
      limit: Limit,
    }),
    ValidateProcessDefinitionInput: Schema.Struct({
      definitionId: Uuid,
      definitionVersion: Schema.Int.check(Schema.isBetween({ minimum: 1, maximum: 2_147_483_647 })),
      catalogVersion: Schema.Int.check(Schema.isBetween({ minimum: 1, maximum: 2_147_483_647 })),
      references: Schema.Array(ResolveProcessCatalogInput).check(Schema.isMaxLength(200)),
    }),
    ListProcessRuntimeInstancesInput: Schema.Struct({
      status: Schema.optionalKey(ProcessRuntimeStatus),
      environment: Schema.optionalKey(ProcessEnvironment),
      limit: Limit,
    }),
    ListProcessWorkflowRunsInput: Schema.Struct({
      workflowType: Schema.optionalKey(ProcessWorkflowType),
      status: Schema.optionalKey(ProcessWorkflowRun.fields.status),
      limit: Limit,
    }),
    ListProcessOperatorInboxInput: Schema.Struct({ limit: Limit }),
    ListProcessOperatorControlsInput: Schema.Struct({
      instanceId: Schema.optionalKey(Uuid),
      limit: Limit,
    }),
    OperateRuntimeInput: Schema.Struct({
      action: ProcessOperatorAction,
      idempotencyKey: ShortString,
      reason: NonEmptyString,
    }),
    ApiError,
  })
  const endpoints = RitseiApi.groups.Process.endpoints
  return [
    "// Generated by tooling/frontend/contracts.ts. Do not edit.",
    'import * as Schema from "effect/Schema"',
    ...generated,
    `export const processRoutes = ${
      JSON.stringify({
        listCatalog: endpoints.listCatalog.path,
        validateDefinition: endpoints.validateDefinition.path,
        listRuntimeInstances: endpoints.listRuntimeInstances.path,
        listWorkflowRuns: endpoints.listWorkflowRuns.path,
        listOperatorInbox: endpoints.listOperatorInbox.path,
        listOperatorControls: endpoints.listOperatorControls.path,
        operateRuntime: endpoints.operateRuntime.path,
      })
    } as const`,
    "",
  ].join("\n\n")
}

export function authSource(): string {
  const generated = declarations({ AuthProfile, AuthConfiguration, AuthLoginResult, AuthSession })
  const endpoints = RitseiApi.groups.Authentication.endpoints
  return [
    "// Generated by tooling/frontend/contracts.ts. Do not edit.",
    'import * as Schema from "effect/Schema"',
    ...generated,
    `export const authRoutes = ${
      JSON.stringify({
        config: endpoints.config.path,
        devLogin: endpoints.devLogin.path,
        session: endpoints.session.path,
        logout: endpoints.logout.path,
      })
    } as const`,
    "",
  ].join("\n\n")
}

export function partySource(): string {
  const generated = declarations({
    PartyKind,
    PartyRole,
    PartyRelationshipKind,
    PartyRepresentationKind,
    Party,
    PartyDirectoryEntry,
    PartyDetail,
    LegalEntity,
    Branch,
    ExternalIdentifier,
    PartyRelationship,
    PartyRepresentation,
    RelatedPartyPath,
    ListPartiesInput: Schema.Struct({
      search: Schema.optionalKey(NonEmptyString),
      kind: Schema.optionalKey(PartyKind),
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 200 })),
      )),
    }),
    ListRelatedPartyPathsInput: Schema.Struct({
      limit: Schema.optionalKey(Schema.Number.pipe(
        Schema.check(Schema.isInt()),
        Schema.check(Schema.isBetween({ minimum: 1, maximum: 100 })),
      )),
    }),
    CreatePartyInput: Schema.Struct({ kind: PartyKind, name: NonEmptyString }),
    CreateBranchInput: Schema.Struct({
      name: NonEmptyString,
      timezone: Schema.optionalKey(NonEmptyString),
      localTaxRegistration: Schema.optionalKey(NonEmptyString),
      dedicatedJournalCode: Schema.optionalKey(NonEmptyString),
    }),
    AssignPartyRoleInput: Schema.Struct({ role: PartyRole }),
    AttachPartyIdentifierInput: Schema.Struct({
      provider: NonEmptyString,
      scheme: NonEmptyString,
      scope: NonEmptyString,
      legalEntityId: Schema.optionalKey(Uuid),
      value: NonEmptyString,
    }),
    CreatePartyRelationshipInput: Schema.Struct({
      legalEntityId: Uuid,
      kind: PartyRelationshipKind,
    }),
    CreatePartyRepresentationInput: Schema.Struct({
      userAccountId: Uuid,
      kind: PartyRepresentationKind,
    }),
    SetPartyRepresentationActiveInput: Schema.Struct({ active: Schema.Boolean }),
    ApiError,
  })
  const endpoints = RitseiApi.groups.Parties.endpoints
  return [
    "// Generated by tooling/frontend/contracts.ts. Do not edit.",
    'import * as Schema from "effect/Schema"',
    ...generated,
    `export const partyRoutes = ${
      JSON.stringify({
        list: endpoints.list.path,
        get: endpoints.get.path,
        create: endpoints.create.path,
        createLegalEntity: endpoints.createLegalEntity.path,
        createBranch: endpoints.createBranch.path,
        assignRole: endpoints.assignRole.path,
        attachIdentifier: endpoints.attachIdentifier.path,
        createRelationship: endpoints.createRelationship.path,
        createRepresentation: endpoints.createRepresentation.path,
        setRepresentationActive: endpoints.setRepresentationActive.path,
        findRelatedPartyPaths: endpoints.findRelatedPartyPaths.path,
      })
    } as const`,
    "",
  ].join("\n\n")
}

if (import.meta.main) {
  const directory = new URL(
    "../../apps/web/src/shared/contracts/generated/",
    import.meta.url,
  )
  await Deno.mkdir(directory, { recursive: true })
  await Promise.all([
    Deno.writeTextFile(new URL("auth.ts", directory), authSource()),
    Deno.writeTextFile(new URL("identity.ts", directory), source()),
    Deno.writeTextFile(new URL("party.ts", directory), partySource()),
    Deno.writeTextFile(new URL("authorization.ts", directory), authorizationSource()),
    Deno.writeTextFile(new URL("procurement.ts", directory), procurementSource()),
    Deno.writeTextFile(new URL("inventory.ts", directory), inventorySource()),
    Deno.writeTextFile(new URL("sales.ts", directory), salesSource()),
    Deno.writeTextFile(new URL("accounting.ts", directory), accountingSource()),
    Deno.writeTextFile(new URL("process.ts", directory), processSource()),
  ])
}
