export const AccountingCapabilities = {
  legalEntityRead: "accounting.legal_entity.read",
  legalEntityConfigure: "accounting.legal_entity.configure",
  financialEngineActivate: "accounting.financial_engine.activate",
  financialProjectionRebuild: "accounting.financial_projection.rebuild",
  financialEvidenceRecord: "accounting.financial_evidence.record",
  financialEvidenceRead: "accounting.financial_evidence.read",
  financialReconciliationCheckpoint: "accounting.financial_reconciliation.checkpoint",
  accountRead: "accounting.account.read",
  accountCreate: "accounting.account.create",
  journalRead: "accounting.journal.read",
  journalPost: "accounting.journal.post",
  revenueRead: "accounting.revenue.read",
  revenueConfigure: "accounting.revenue.configure",
  periodRead: "accounting.period.read",
  periodOpen: "accounting.period.open",
  periodClose: "accounting.period.close",
  revenuePost: "accounting.revenue.post",
  revenueReverse: "accounting.revenue.reverse",
} as const
