import { css } from "../generated/css/index.js"

// Approved shell/workspace layouts. Features consume names, not arbitrary style properties.
export const layout = {
  page: css({
    minHeight: "screen",
    bg: "canvas",
    color: "text",
    overflowX: "hidden",
  }),
  topbar: css({
    minHeight: "12",
    display: "grid",
    gridTemplateColumns: "auto auto minmax(0, 1fr) auto",
    alignItems: "center",
    gap: { base: "2", md: "3" },
    px: { base: "2", md: "3" },
    borderBottomWidth: "1px",
    borderColor: "boundary",
    bg: "content",
  }),
  brand: css({
    display: "inline-flex",
    alignItems: "center",
    color: "text",
    bg: "surface",
    textDecoration: "none",
    borderRadius: "sm",
    minHeight: "10",
    px: "2",
  }),
  brandLogo: css({
    display: "block",
    width: { base: "20", md: "28" },
    height: "auto",
  }),
  navigationToggle: css({ flexShrink: "0" }),
  contextStrip: css({
    minWidth: "0",
    display: "flex",
    alignItems: "center",
    gap: "1",
    overflow: "hidden",
  }),
  contextItem: css({
    minWidth: "0",
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    alignItems: "baseline",
    gap: "2",
    px: "3",
    py: "1",
    borderLeftWidth: "1px",
    borderColor: "boundary",
    whiteSpace: "nowrap",
  }),
  contextItemOptional: css({ display: { base: "none", lg: "grid" } }),
  contextLabel: css({
    textStyle: "metadata",
    color: "muted",
  }),
  contextValue: css({
    minWidth: "0",
    maxWidth: "40",
    overflow: "hidden",
    textOverflow: "ellipsis",
    textStyle: "label",
  }),
  contextCode: css({ fontFamily: "mono", fontVariantNumeric: "tabular-nums" }),
  topbarActions: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "2",
  }),
  previewBadge: css({
    display: { base: "none", md: "inline-flex" },
    alignItems: "center",
    minHeight: "6",
    px: "2",
    borderWidth: "1px",
    borderColor: "boundary",
    borderRadius: "sm",
    color: "muted",
    textStyle: "metadata",
  }),
  shellBody: css({
    minHeight: "shellViewport",
    display: "grid",
    gridTemplateColumns: { base: "minmax(0, 1fr)", md: "14rem minmax(0, 1fr)" },
    alignItems: "stretch",
    transitionProperty: "size",
    transitionDuration: "normal",
    transitionTimingFunction: "standard",
    _motionReduce: { transitionDuration: "none" },
  }),
  shellBodyCollapsed: css({
    gridTemplateColumns: { base: "minmax(0, 1fr)", md: "4rem minmax(0, 1fr)" },
  }),
  sidebar: css({
    position: { base: "fixed", md: "sticky" },
    top: { base: "12", md: "0" },
    left: "0",
    zIndex: "modal",
    width: { base: "56", md: "auto" },
    height: "shellViewport",
    minWidth: "0",
    display: "flex",
    flexDirection: "column",
    overflowY: "auto",
    overscrollBehavior: "contain",
    bg: "ink",
    color: "surface",
    backgroundImage:
      "radial-gradient(circle at 8% 4%, rgba(167,187,196,0.12), transparent 36%), repeating-radial-gradient(circle at 18% 12%, transparent 0 22px, rgba(250,248,242,0.045) 23px 24px)",
    borderRightWidth: "1px",
    borderColor: "slate",
    transform: { base: "translateX(-100%)", md: "none" },
    transitionProperty: "common",
    transitionDuration: "normal",
    transitionTimingFunction: "standard",
    _motionReduce: { transitionDuration: "none" },
    "&[data-mobile-open=true]": { transform: "translateX(0)" },
    "&[data-collapsed=true]": { width: { base: "56", md: "16" } },
  }),
  navigationBackdrop: css({
    position: "fixed",
    top: "12",
    right: "0",
    bottom: "0",
    left: "0",
    zIndex: "modal",
    display: { base: "block", md: "none" },
    padding: "0",
    border: "none",
    bg: "backdrop",
    cursor: "default",
  }),
  navigation: css({
    display: "flex",
    flexDirection: "column",
    gap: "5",
    px: "2",
    py: "4",
  }),
  navigationSection: css({ display: "grid", gap: "1" }),
  navigationSectionLabel: css({
    m: "0",
    minHeight: "5",
    px: "3",
    color: "surface",
    opacity: "0.62",
    textStyle: "helper",
    whiteSpace: "nowrap",
  }),
  navigationSectionLabelCollapsed: css({
    display: { base: "block", md: "none" },
  }),
  navigationList: css({ display: "grid", gap: "1" }),
  navigationItem: css({
    minHeight: "10",
    minWidth: "10",
    display: "flex",
    alignItems: "center",
    gap: "3",
    px: "3",
    borderRadius: "sm",
    color: "surface",
    textDecoration: "none",
    textStyle: "label",
    whiteSpace: "nowrap",
    _hover: { bg: "slate" },
    "&[data-active]": {
      bg: "terrain",
      color: "surface",
      "@media (forced-colors: active)": {
        forcedColorAdjust: "none",
        background: "[Highlight]",
        color: "[HighlightText]",
        borderColor: "[Highlight]",
      },
    },
  }),
  navigationItemUnavailable: css({
    color: "surface",
    opacity: "0.58",
    cursor: "not-allowed",
    _hover: { bg: "transparent" },
  }),
  navigationMarker: css({
    width: "7",
    height: "7",
    flexShrink: "0",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: "1px",
    borderColor: "slate",
    borderRadius: "sm",
    fontFamily: "mono",
    fontSize: "xs",
    lineHeight: "none",
    fontVariantNumeric: "tabular-nums",
  }),
  navigationLabel: css({ overflow: "hidden", textOverflow: "ellipsis" }),
  navigationLabelCollapsed: css({ display: { base: "inline", md: "none" } }),
  sidebarNote: css({
    mt: "auto",
    mb: "0",
    px: "5",
    py: "4",
    borderTopWidth: "1px",
    borderColor: "slate",
    color: "surface",
    opacity: "0.72",
    textStyle: "helper",
  }),
  sidebarNoteCollapsed: css({ display: { base: "block", md: "none" } }),
  workspace: css({ minWidth: "0", bg: "canvas" }),
  localNavigation: css({
    minHeight: "10",
    display: "flex",
    alignItems: "center",
    gap: "5",
    px: { base: "4", md: "6" },
    overflowX: "auto",
    borderBottomWidth: "1px",
    borderColor: "boundary",
    bg: "content",
  }),
  localArea: css({
    flexShrink: "0",
    color: "muted",
    textStyle: "metadata",
  }),
  localNavigationLinks: css({
    minWidth: "0",
    display: "flex",
    alignItems: "stretch",
    alignSelf: "stretch",
    gap: "4",
    whiteSpace: "nowrap",
    "& a": {
      display: "inline-flex",
      alignItems: "center",
      color: "text",
      textDecoration: "none",
      textStyle: "label",
      borderBottomWidth: "2px",
      borderColor: "transparent",
    },
    "& a[data-active]": {
      color: "action",
      borderColor: "action",
      "@media (forced-colors: active)": {
        forcedColorAdjust: "none",
        background: "[Highlight]",
        color: "[HighlightText]",
        borderColor: "[Highlight]",
      },
    },
  }),
  main: css({
    minWidth: "0",
    width: "full",
    px: { base: "4", md: "6", lg: "8" },
    py: { base: "6", md: "8" },
    minHeight: "96",
  }),
  header: css({
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "6",
    px: "6",
    py: "4",
    borderBottomWidth: "1px",
    borderColor: "boundary",
  }),
  wordmark: css({
    textStyle: "label",
    letterSpacing: "label",
    textDecoration: "none",
    color: "text",
  }),
  notice: css({
    bg: "content",
    color: "muted",
    textStyle: "metadata",
    px: "6",
    py: "2",
    borderBottomWidth: "1px",
    borderColor: "boundary",
  }),
  stack: css({
    display: "flex",
    flexDirection: "column",
    gap: "4",
    minWidth: "0",
  }),
  row: css({
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "3",
  }),
  workspaceSplit: css({
    display: "grid",
    gridTemplateColumns: {
      base: "minmax(0, 1fr)",
      xl: "minmax(0, 1.6fr) minmax(18rem, 0.8fr)",
    },
    alignItems: "start",
    gap: "4",
    minWidth: "0",
  }),
  contentGrid: css({
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(18rem, 1fr))",
    gap: "4",
  }),
  tableWrap: css({ overflowX: "auto" }),
  table: css({ width: "full", borderCollapse: "collapse" }),
  tableCell: css({
    borderBottomWidth: "1px",
    borderColor: "boundary",
    px: "3",
    py: "2",
    textAlign: "left",
    verticalAlign: "top",
  }),
  actionRow: css({ display: "flex", flexWrap: "wrap", gap: "2", alignItems: "center" }),
  designerHost: css({
    overflow: "hidden",
    borderWidth: "1px",
    borderColor: "boundary",
    borderRadius: "md",
  }),
  detailList: css({
    display: "grid",
    gap: "3",
    m: "0",
  }),
  detailItem: css({
    display: "grid",
    gridTemplateColumns: "minmax(7rem, auto) minmax(0, 1fr)",
    alignItems: "baseline",
    gap: "3",
    py: "2",
    borderBottomWidth: "1px",
    borderColor: "boundary",
  }),
  detailTerm: css({ color: "muted", textStyle: "metadata" }),
  detailValue: css({ m: "0", minWidth: "0", overflowWrap: "anywhere" }),
  code: css({ fontFamily: "mono", fontVariantNumeric: "tabular-nums" }),
  muted: css({ color: "muted" }),
  tableRowSelected: css({ bg: "surface" }),
  footer: css({
    px: "6",
    py: "4",
    color: "muted",
    textStyle: "metadata",
    borderTopWidth: "1px",
    borderColor: "boundary",
  }),
  scroll: css({ overflowX: "auto" }),
  skip: css({
    position: "absolute",
    top: "2",
    left: "2",
    zIndex: "skipLink",
    p: "3",
    bg: "content",
    transform: "translateY(-200%)",
    _focus: { transform: "none" },
  }),
}
