import { css } from "../generated/css/index.js"

// Approved shell/workspace layouts. Features consume names, not arbitrary style properties.
export const layout = {
  page: css({
    minHeight: "screen",
    bg: "canvas",
    color: "text",
    overflowX: "hidden",
  }),
  topbar: css({
    minHeight: "12",
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: { base: "1", md: "2" },
    px: { base: "2", md: "4" },
    borderBottomWidth: "1px",
    borderColor: "boundary",
    bg: "content",
  }),
  brand: css({
    display: "inline-flex",
    alignItems: "center",
    color: "text",
    textDecoration: "none",
    minHeight: "10",
    px: "1",
  }),
  brandLogo: css({
    display: "block",
    width: { base: "20", md: "28" },
    height: "auto",
    _dark: { filter: "[brightness(0) invert(0.9)]" },
  }),
  navigationToggle: css({ flexShrink: "0" }),
  contextStrip: css({
    minWidth: "0",
    flexGrow: "1",
    display: { base: "none", md: "flex" },
    alignItems: "center",
    gap: "1",
    overflow: "hidden",
  }),
  contextItem: css({
    minWidth: "0",
    display: "grid",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    alignItems: "baseline",
    gap: "2",
    px: "3",
    py: "1",
    borderLeftWidth: "1px",
    borderColor: "boundary",
    whiteSpace: "nowrap",
  }),
  contextLabel: css({
    textStyle: "metadata",
    color: "muted",
  }),
  contextValue: css({
    minWidth: "0",
    maxWidth: "40",
    overflow: "hidden",
    textOverflow: "ellipsis",
    textStyle: "label",
  }),
  contextCode: css({ fontFamily: "mono", fontVariantNumeric: "tabular-nums" }),
  topbarActions: css({
    display: "flex",
    ml: "auto",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "2",
  }),
  shellBody: css({
    minHeight: "shellViewport",
    display: "grid",
    gridTemplateColumns: { base: "minmax(0, 1fr)", md: "13rem minmax(0, 1fr)" },
    alignItems: "stretch",
    transitionProperty: "size",
    transitionDuration: "normal",
    transitionTimingFunction: "standard",
    _motionReduce: { transitionDuration: "none" },
  }),
  shellBodyCollapsed: css({
    gridTemplateColumns: { base: "minmax(0, 1fr)", md: "4rem minmax(0, 1fr)" },
  }),
  sidebar: css({
    position: { base: "fixed", md: "sticky" },
    top: { base: "12", md: "0" },
    left: "0",
    zIndex: "modal",
    width: { base: "56", md: "auto" },
    height: "shellViewport",
    minWidth: "0",
    display: "flex",
    flexDirection: "column",
    overflowY: "auto",
    overscrollBehavior: "contain",
    bg: "ink",
    color: "surface",
    borderRightWidth: "1px",
    borderColor: "slate",
    "@media (forced-colors: active)": { bg: "[Canvas]", color: "[CanvasText]" },
    transform: { base: "translateX(-100%)", md: "none" },
    transitionProperty: "common",
    transitionDuration: "normal",
    transitionTimingFunction: "standard",
    _motionReduce: { transitionDuration: "none" },
    "&[data-mobile-open=true]": { transform: "translateX(0)" },
    "&[data-collapsed=true]": { width: { base: "56", md: "16" } },
  }),
  navigationBackdrop: css({
    position: "fixed",
    top: "12",
    right: "0",
    bottom: "0",
    left: "0",
    zIndex: "modal",
    display: { base: "block", md: "none" },
    padding: "0",
    border: "none",
    bg: "backdrop",
    cursor: "default",
  }),
  navigation: css({
    display: "flex",
    flexDirection: "column",
    gap: "4",
    px: "2",
    py: "4",
  }),
  navigationSection: css({ display: "grid", gap: "1" }),
  navigationSectionLabel: css({
    m: "0",
    minHeight: "5",
    px: "3",
    color: "surface",
    opacity: "0.7",
    textStyle: "helper",
    whiteSpace: "nowrap",
    "@media (forced-colors: active)": { color: "[CanvasText]" },
  }),
  navigationSectionLabelCollapsed: css({
    display: { base: "block", md: "none" },
  }),
  navigationList: css({ display: "grid", gap: "1" }),
  navigationItem: css({
    minHeight: "9",
    minWidth: "10",
    display: "flex",
    alignItems: "center",
    gap: "2",
    px: "2",
    borderLeftWidth: "2px",
    borderColor: "transparent",
    color: "surface",
    textDecoration: "none",
    textStyle: "label",
    whiteSpace: "nowrap",
    "@media (forced-colors: active)": { color: "[CanvasText]" },
    _hover: { bg: "slate" },
    "&[data-active]": {
      bg: "slate",
      borderColor: "surface",
      color: "surface",
      "@media (forced-colors: active)": {
        forcedColorAdjust: "none",
        background: "[Highlight]",
        color: "[HighlightText]",
        borderColor: "[Highlight]",
        "& span:first-child": { color: "[HighlightText]", opacity: "1" },
      },
    },
  }),
  navigationMarker: css({
    width: "7",
    flexShrink: "0",
    color: "surface",
    opacity: "0.65",
    fontFamily: "mono",
    fontSize: "xs",
    fontVariantNumeric: "tabular-nums",
    "@media (forced-colors: active)": { color: "[CanvasText]" },
  }),
  navigationLabel: css({ overflow: "hidden", textOverflow: "ellipsis" }),
  navigationLabelCollapsed: css({ display: { base: "inline", md: "none" } }),
  workspace: css({ minWidth: "0", bg: "canvas" }),
  localNavigation: css({
    minHeight: "10",
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "3",
    px: { base: "4", md: "6" },
    overflowX: "auto",
    borderBottomWidth: "1px",
    borderColor: "boundary",
    bg: "content",
  }),
  localArea: css({
    flexShrink: "0",
    color: "muted",
    textStyle: "metadata",
  }),
  localTenant: css({
    display: { base: "block", md: "none" },
    minWidth: "0",
    ml: "auto",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "muted",
    fontFamily: "mono",
    fontSize: "xs",
  }),
  localNavigationLinks: css({
    minWidth: "0",
    display: "flex",
    alignItems: "stretch",
    alignSelf: "stretch",
    gap: "4",
    whiteSpace: "nowrap",
    "& a": {
      display: "inline-flex",
      alignItems: "center",
      color: "text",
      textDecoration: "none",
      textStyle: "label",
      borderBottomWidth: "1px",
      borderColor: "transparent",
    },
    "& a[data-active]": {
      color: "text",
      borderColor: "boundary",
      "@media (forced-colors: active)": {
        forcedColorAdjust: "none",
        background: "[Highlight]",
        color: "[HighlightText]",
        borderColor: "[Highlight]",
      },
    },
  }),
  main: css({
    minWidth: "0",
    width: "full",
    px: { base: "4", md: "6", lg: "8" },
    py: { base: "5", md: "6" },
    minHeight: "96",
  }),
  header: css({
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "6",
    px: "6",
    py: "4",
    borderBottomWidth: "1px",
    borderColor: "boundary",
  }),
  wordmark: css({
    textStyle: "label",
    letterSpacing: "label",
    textDecoration: "none",
    color: "text",
  }),
  notice: css({
    bg: "content",
    color: "muted",
    textStyle: "metadata",
    px: "6",
    py: "2",
    borderBottomWidth: "1px",
    borderColor: "boundary",
  }),
  stack: css({
    display: "flex",
    flexDirection: "column",
    gap: "4",
    minWidth: "0",
  }),
  row: css({
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "3",
  }),
  workspaceSplit: css({
    display: "grid",
    gridTemplateColumns: {
      base: "minmax(0, 1fr)",
      xl: "minmax(0, 1.6fr) minmax(18rem, 0.8fr)",
    },
    alignItems: "start",
    gap: "4",
    minWidth: "0",
  }),
  contentGrid: css({
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(18rem, 1fr))",
    gap: "4",
  }),
  tableWrap: css({ overflowX: "auto" }),
  table: css({ width: "full", borderCollapse: "collapse" }),
  tableCell: css({
    borderBottomWidth: "1px",
    borderColor: "boundary",
    px: "3",
    py: "2",
    textAlign: "left",
    verticalAlign: "top",
  }),
  actionRow: css({ display: "flex", flexWrap: "wrap", gap: "2", alignItems: "center" }),
  designerHost: css({
    overflow: "hidden",
    borderWidth: "1px",
    borderColor: "boundary",
    borderRadius: "md",
  }),
  detailList: css({
    display: "grid",
    gap: "3",
    m: "0",
  }),
  detailItem: css({
    display: "grid",
    gridTemplateColumns: "minmax(7rem, auto) minmax(0, 1fr)",
    alignItems: "baseline",
    gap: "3",
    py: "2",
    borderBottomWidth: "1px",
    borderColor: "boundary",
  }),
  detailTerm: css({ color: "muted", textStyle: "metadata" }),
  detailValue: css({ m: "0", minWidth: "0", overflowWrap: "anywhere" }),
  code: css({ fontFamily: "mono", fontVariantNumeric: "tabular-nums" }),
  muted: css({ color: "muted" }),
  tableRowSelected: css({ bg: "content" }),
  workspaceHeading: css({
    display: "flex",
    flexWrap: "wrap",
    alignItems: "end",
    justifyContent: "space-between",
    gap: "4",
    pb: "5",
    borderBottomWidth: "1px",
    borderColor: "boundary",
  }),
  workspaceTitle: css({ display: "grid", gap: "2" }),
  workspaceDescription: css({ color: "muted", maxWidth: "3xl", m: "0" }),
  collectionToolbar: css({
    display: "flex",
    flexWrap: "wrap",
    alignItems: "end",
    justifyContent: "space-between",
    gap: "3",
    py: "4",
  }),
  collectionControls: css({ display: "flex", flexWrap: "wrap", gap: "2", alignItems: "end" }),
  searchField: css({ width: { base: "full", sm: "64" }, maxWidth: "full" }),
  filterField: css({ width: { base: "full", sm: "40" } }),
  filterSelect: css({
    minHeight: "11",
    width: "full",
    px: "3",
    bg: "content",
    color: "text",
    borderWidth: "1px",
    borderColor: "boundary",
    borderRadius: "sm",
    textStyle: "body",
    _focusVisible: { outline: "[3px solid]", outlineColor: "action", outlineOffset: "[2px]" },
  }),
  fieldLabel: css({ display: "grid", gap: "1", color: "muted", textStyle: "metadata" }),
  resultCount: css({ textStyle: "label", color: "muted", m: "0" }),
  collectionTable: css({
    width: "full",
    tableLayout: "fixed",
    "& caption": {
      position: "absolute",
      width: "[1px]",
      height: "[1px]",
      p: "0",
      overflow: "hidden",
      clip: "rect(0, 0, 0, 0)",
      whiteSpace: "nowrap",
    },
    "& thead": { bg: "content" },
    "& th": { color: "muted", textStyle: "tableHeader" },
    "& th:first-child": { width: { base: "[58%]", md: "[34%]" } },
    "& th:nth-child(2)": { width: { md: "[36%]" } },
    "& th:nth-child(2), & td:nth-child(2)": { display: { base: "none", md: "table-cell" } },
    "& th:nth-child(3)": { width: { base: "[24%]", md: "[18%]" } },
    "& th:last-child": { width: { base: "[18%]", md: "[12%]" } },
    "& th:last-child, & td:last-child": { textAlign: "end" },
    "& tbody tr:hover, & tbody tr:focus-within": { bg: "content" },
    "& td, & tbody th": { py: "3" },
  }),
  rowIdentity: css({ display: "grid", gap: "1", minWidth: "0" }),
  rowReference: css({
    display: "block",
    color: "muted",
    fontFamily: "mono",
    fontSize: "xs",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  }),
  mobileReference: css({ display: { base: "block", md: "none" } }),
  statusText: css({ display: "inline-flex", alignItems: "center", gap: "2", textStyle: "status" }),
  statusActive: css({ color: "icon.success" }),
  statusDisabled: css({ color: "icon.warning" }),
  quietLink: css({ textDecoration: "none", _hover: { textDecoration: "underline" } }),
  documentGrid: css({
    display: "grid",
    gridTemplateColumns: { base: "minmax(0, 1fr)", lg: "minmax(0, 1.7fr) minmax(15rem, 0.8fr)" },
    gap: { base: "6", lg: "8" },
    pt: "5",
  }),
  documentSection: css({
    minWidth: "0",
    borderTopWidth: "1px",
    borderColor: "boundary",
    pt: "4",
  }),
  documentAside: css({
    minWidth: "0",
    borderTopWidth: { base: "1px", lg: "0" },
    borderLeftWidth: { base: "0", lg: "1px" },
    borderColor: "boundary",
    pt: { base: "4", lg: "0" },
    pl: { base: "0", lg: "6" },
  }),
  objectMetadata: css({ display: "flex", flexWrap: "wrap", alignItems: "center", gap: "3" }),
  objectReference: css({
    fontFamily: "mono",
    fontSize: "xs",
    color: "muted",
    overflowWrap: "anywhere",
  }),
  formArea: css({ maxWidth: "2xl", display: "grid", gap: "4" }),
  formActions: css({
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "2",
    pt: "4",
    borderTopWidth: "1px",
    borderColor: "boundary",
  }),
  emptyCollection: css({ borderTopWidth: "1px", borderColor: "boundary", py: "8" }),
  directoryList: css({
    display: "grid",
    gridTemplateColumns: { base: "minmax(0, 1fr)", md: "repeat(2, minmax(0, 1fr))" },
    columnGap: "6",
    listStyle: "none",
    m: "0",
    p: "0",
    "& li": { borderTopWidth: "1px", borderColor: "boundary" },
    "& a": { display: "block", py: "4", textDecoration: "none" },
    "& a:hover": { textDecoration: "underline" },
  }),
  footer: css({
    px: "6",
    py: "4",
    color: "muted",
    textStyle: "metadata",
    borderTopWidth: "1px",
    borderColor: "boundary",
  }),
  scroll: css({ overflowX: "auto" }),
  skip: css({
    position: "absolute",
    top: "2",
    left: "2",
    zIndex: "skipLink",
    p: "3",
    bg: "content",
    transform: "translateY(-200%)",
    _focus: { transform: "none" },
  }),
}
